Added fake EDDN Listener
EDCD/EDMarketConnector pull request #1093
Opened 2021-05-21 07:11 UTC by A-UNDERSCORE-D

A simple HTTP handler has been added that will dump any and all POST
data it gets to EDMC's log.

Additionally, a new command line argument to switch EDMC to using this
as its EDDN target has been added.

!! This needs testing before merging.

2021-05-21 07:53 UTC, Athanasius commented
Ooooh, no, I didn't want this going into application logging, it needs to be the raw data out to its own file.

`%TEMP/EDMarketConnector-EDDN-log.txt` or the like.

2021-05-21 07:53 UTC, Athanasius commented
> Ooooh, no, I didn't want this going into application logging, it needs to be the raw data out to its own file.
> 
> `%TEMP/EDMarketConnector-EDDN-log.txt` or the like.

To be clear, this goes into its own file so it's pure JSONL, without the usual logging timestamp/module prefixing.

2021-05-21 08:44 UTC, A-UNDERSCORE-D commented
oh I can do that too. One moment

2021-05-23 10:56 UTC, Athanasius commented
This should be extended for a CL arg per other thing we send to.

EDSM
Inara

*Maybe* also the 'providers' ?

The basic idea being able to test functionality without sending possibly bad data to the live services.  Make debugging easier.

2021-05-25 09:12 UTC, A-UNDERSCORE-D commented
I've replaced the original implementation with support for arbitrary POSTs, on disk they're organized by path (please check anti-traversal magic, it should be fine.) and configured via CL arg that is repeated for any name you want to support.

2021-06-18 21:42 UTC, A-UNDERSCORE-D commented
Rebased against develop

2021-06-19 08:56 UTC, Athanasius requested changes
Only cosmetics for now.  I should actually try out the code ....

2021-06-19 08:56 UTC, Athanasius commented on PLUGINS.md
> +logs exist in `$TEMP/EDMarketConnector/http_debug/$path.log`. If somehow you manage to cause a directory traversal, your
s/logs/Logs/

2021-06-19 08:56 UTC, Athanasius commented on debug_webserver.py
> +            logger.warn(f'DATA FOLLOWS\n{data}')
Shoud be logger.warning

2021-06-19 08:56 UTC, Athanasius commented on debug_webserver.py
> +        self.end_headers()  # This is needed because send_response_only DOESN'T ACTUALLY SEND THE RESPONSE </rant>
Blank line after conditional

2021-06-19 08:56 UTC, Athanasius commented on plugins/edsm.py
>  def worker() -> None:
Might as well # noqa this.

At some point in the future we'll get around to grepping for all such and see about refactors.  Reduce the noise for now.

2021-06-19 09:06 UTC, Athanasius commented
And now I've actually run it, including debugging both EDDN and Inara at the same time, yup, looks good once those niggles are addressed.

2021-06-20 17:02 UTC, Athanasius approved these changes

2021-06-20 17:02 UTC, merged