re #1198 work around +size suffixes in CAPI responses
EDCD/EDMarketConnector pull request #1220
Opened 2021-08-06 19:37 UTC by inorton

Strip the extra + chars in surface port names that are wrongly returned by the CAPI.

Also rely on station ID checks rather than name comparison before we assume the CAPI is lagging

2021-08-06 19:41 UTC, A-UNDERSCORE-D requested changes

2021-08-06 19:41 UTC, A-UNDERSCORE-D commented on companion.py
> +        # strip "+" chars off star port names returned by the CAPI
```suggestion
        # WORKAROUND: n/a | 06-08-2021: Issue 1198 and https://issues.frontierstore.net/issue-detail/40706 -- strip "+" chars off star port names returned by the CAPI
```

2021-08-06 19:41 UTC, A-UNDERSCORE-D commented on companion.py
```suggestion
# WORKAROUND END

```

2021-08-06 19:43 UTC, A-UNDERSCORE-D commented
Please switch this to point at `develop`, other than the requested comment changes to fit with [the new standard](https://github.com/EDCD/EDMarketConnector/blob/main/Contributing.md#comments) this LGTM

2021-08-06 20:25 UTC, A-UNDERSCORE-D approved these changes

2021-08-06 20:25 UTC, A-UNDERSCORE-D commented
Looks good, should work fine but Ill let @Athanasius give it a look over in case I missed any gotchas

2021-08-07 12:05 UTC, Athanasius commented
> Looks good, should work fine but Ill let @Athanasius give it a look over in case I missed any gotchas

That all looks good, I'll give it a test this afternoon and then merge if I don't run into any issues.

2021-08-07 13:03 UTC, merged