Converted all old os.path related library use to Pathlib. 18 files.
EDCD/EDMarketConnector pull request #2254
Opened 2024-06-07 02:21 UTC by Michael-K-Williams

# Description
This is a PR for replacing all of the old uses of os.path and its' various functions to all rest under pathlib.

# Type of Change
**Enhancement**

# How Tested
Loaded program straight from source on Linux, repaired all initial errors. No new errors.

# Notes
https://github.com/EDCD/EDMarketConnector/issues/2114

Issue 2114, Enhancement.

Additionally added extra logging niceness when the journal file errors 'none', making it state in brackets to check their config file, as there will be users who will run this from the terminal.

Tested on Linux Distro EndeavourOS, with Kernel "6.9.3-arch1-1"

2024-06-07 09:01 UTC, Michael-K-Williams commented
Fixed the few errors that happened last time it checked the code (my bad) and reverted the oldconfig file to its' original state.

2024-06-10 14:34 UTC, Rixxan requested changes
It looks like our linters are rather unhappy with the changes in here. Can this be reviewed, please?

```
(venv) PS D:\Users\david\Documents\GitHub\EDMarketConnector> mypy $(git ls-files '*.py')
commodity.py:31: error: "type[Path]" has no attribute "join"  [attr-defined]
l10n.py:126: error: Invalid index type "Path" for "dict[str | None, dict[str, str]]"; expected type "str | None"  [index]
l10n.py:183: error: Incompatible types in assignment (expression has type "Path", variable has type "str | None")  [assignment]
dashboard.py:63: error: Too many arguments for "stop" of "Dashboard"  [call-arg]
EDMCSystemProfiler.py:22: error: "Path" has no attribute "chdir"  [attr-defined]
EDMCSystemProfiler.py:29: error: "Path" has no attribute "chdir"  [attr-defined]
build.py:90: error: "str" has no attribute "iterdir"  [attr-defined]
plug.py:174: error: Argument 2 to "Plugin" has incompatible type "Path"; expected "str | None"  [arg-type]
plug.py:200: error: Argument 2 to "Plugin" has incompatible type "Path"; expected "str | None"  [arg-type]
prefs.py:1091: error: "Path" has no attribute "lower"  [attr-defined]
prefs.py:1098: error: Name "expandvars" is not defined  [name-defined]
EDMarketConnector.py:37: error: Module has no attribute "joinlib"  [attr-defined]
EDMarketConnector.py:38: error: Module has no attribute "joinlib"  [attr-defined]
EDMarketConnector.py:54: error: Module has no attribute "joinlib"  [attr-defined]
EDMarketConnector.py:1641: error: Module has no attribute "joinlib"  [attr-defined]
```
```
(venv) PS D:\Users\david\Documents\GitHub\EDMarketConnector> flake8 $(git ls-files '*.py')
EDMCSystemProfiler.py:117:17: E251 unexpected spaces around keyword / parameter equals
EDMCSystemProfiler.py:117:19: E251 unexpected spaces around keyword / parameter equals
EDMarketConnector.py:471:25: E128 continuation line under-indented for visual indent
EDMarketConnector.py:2020:17: F402 import 'kill' from line 14 shadowed by loop variable
l10n.py:213:1: W293 blank line contains whitespace
l10n.py:229:5: E303 too many blank lines (2)
l10n.py:385:121: E501 line too long (134 > 120 characters)
monitor.py:207:121: E501 line too long (128 > 120 characters)
prefs.py:1078:5: CCR001 Cognitive complexity is too high (17 > 15)
prefs.py:1098:54: F821 undefined name 'expandvars'
prefs.py:1239:121: E501 line too long (138 > 120 characters)
tests/config/_old_config.py:407:25: W292 no newline at end of file
```

2024-06-10 18:14 UTC, ElSaico commented on prefs.py
> +            home_path = Path(config.home)
There's already a `Path` equivalent, which is `config.home_path`.

2024-06-10 18:14 UTC, ElSaico commented on prefs.py
> +            home_path = Path(config.home)
There's already a `Path` equivalent, which is `config.home_path`.

2024-06-10 18:14 UTC, ElSaico commented on prefs.py
> +    profiler_path = Path(config.respath_path)
This is already a `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on plug.py
> +    internal_plugin_dir = Path(config.internal_plugin_dir_path)
This is already a `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on EDMCLogging.py
> +        internal_plugin_dir = Path(config.internal_plugin_dir_path).expanduser()
The latter two are already `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on EDMCSystemProfiler.py
> +            file = str(Path(cur_config.respath_path) / "io.edcd.EDMarketConnector.png")
This is already a `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on EDMCSystemProfiler.py
> +        root.iconbitmap(str(Path(cur_config.respath_path) / "EDMarketConnector.ico"))
This is already a `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on EDMarketConnector.py
> +            self.w.tk.call('wm', 'iconphoto', self.w, '-default', tk.PhotoImage(file=Path(config.respath_path) / 'io.edcd.EDMarketConnector.png'))
This is already a `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on EDMarketConnector.py
> +        file_name = join(config.app_dir_path, "last_shipyard.html")
This is a `Path`, so the `/` operator would be preferable here.

2024-06-10 18:14 UTC, ElSaico commented on companion.py
> +            if not (Path(config.respath_path) / 'FDevIDs' / f).is_file():
This is already a `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on l10n.py
> +        plugin_dir = Path(config.plugin_dir_path)
This is already a `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on l10n.py
> +        plugin_path = Path(config.plugin_dir_path) / plugin_name / LOCALISATION_DIR
This is already a `Path`, no need to convert.

2024-06-10 18:14 UTC, ElSaico commented on l10n.py
> +            plugin_path = Path(config.plugin_dir_path) / plugin_name / LOCALISATION_DIR
This is already a `Path`, no need to convert.

2024-06-10 18:15 UTC, closed without merging